In [ ]:
import numpy as np
np.random.seed(42)
A = np.random.randint(1, 11, size=(4, 3))

print("Matrix A:")
print(A)
print("Shape of A:", A.shape)

B = np.random.randint(1, 11, size=(3, 5))

print("\nMatrix B:")
print(B)
print("Shape of B:", B.shape)

assert A.shape[1] == B.shape[0]

print("\nInner dimensions match.")

C = np.dot(A, B)

print("\nMatrix C = A dot B:")
print(C)
print("Shape of C:", C.shape)


assert C.shape == (4, 5)

print("Output shape verified: (4, 5)")


total_sum = np.sum(C)

print("\nTotal sum of C:", total_sum)


row_sums = np.sum(C, axis=1)

print("\nRow-wise sums:")
print(row_sums)


column_sums = np.sum(C, axis=0)

print("\nColumn-wise sums:")
print(column_sums)

Matrix A:
[[ 7  4  8]
 [ 5  7 10]
 [ 3  7  8]
 [ 5  4  8]]
Shape of A: (4, 3)

Matrix B:
[[ 8  3  6  5  2]
 [ 8  6  2  5  1]
 [10  6  9  1 10]]
Shape of B: (3, 5)

Inner dimensions match.

Matrix C = A dot B:
[[168  93 122  63  98]
 [196 117 134  70 117]
 [160  99 104  58  93]
 [152  87 110  53  94]]
Shape of C: (4, 5)
Output shape verified: (4, 5)

Total sum of C: 2188

Row-wise sums:
[544 634 514 496]

Column-wise sums:
[676 396 470 244 402]
